// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpQIMBueqBd5c8tMtidkjR3NcBxboljBk',
    appId: '1:50486225211:web:3bc64e9aa349fcb600af1e',
    messagingSenderId: '50486225211',
    projectId: 'shoppapp-3f613',
    authDomain: 'shoppapp-3f613.firebaseapp.com',
    databaseURL: 'https://shoppapp-3f613-default-rtdb.firebaseio.com',
    storageBucket: 'shoppapp-3f613.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGrqplvZzkL0Wg9UFzP4BGoMFdfiB9IWQ',
    appId: '1:50486225211:android:8292c637cdda9ec600af1e',
    messagingSenderId: '50486225211',
    projectId: 'shoppapp-3f613',
    databaseURL: 'https://shoppapp-3f613-default-rtdb.firebaseio.com',
    storageBucket: 'shoppapp-3f613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoe6D_udqp5r5_skWvDHWdHoh7JxNl5_c',
    appId: '1:50486225211:ios:385331f9746b904500af1e',
    messagingSenderId: '50486225211',
    projectId: 'shoppapp-3f613',
    databaseURL: 'https://shoppapp-3f613-default-rtdb.firebaseio.com',
    storageBucket: 'shoppapp-3f613.appspot.com',
    iosClientId: '50486225211-sv73oaqe7lk0uhvlvnli133id5lhr5a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoe6D_udqp5r5_skWvDHWdHoh7JxNl5_c',
    appId: '1:50486225211:ios:385331f9746b904500af1e',
    messagingSenderId: '50486225211',
    projectId: 'shoppapp-3f613',
    databaseURL: 'https://shoppapp-3f613-default-rtdb.firebaseio.com',
    storageBucket: 'shoppapp-3f613.appspot.com',
    iosClientId: '50486225211-sv73oaqe7lk0uhvlvnli133id5lhr5a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppapp',
  );
}
